
filetype on
filetype plugin on
filetype indent on

set mouse=a
set mousefocus
set number

set shiftwidth=4
set tabstop=2
" set softtabstop=4

set ruler
set hlsearch

" On pressing tab, insert 4 spaces
set expandtab
set autoindent

syntax on
colorscheme elflord
colorscheme gotham256

set wildmenu
set wildmode=longest,full

nmap <silent> <C-Up> :wincmd k<CR>
nmap <silent> <C-Down> :wincmd j<CR>
nmap <silent> <C-Left> :wincmd h<CR>
nmap <silent> <C-Right> :wincmd l<CR>

" NerdTree like netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 15
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END

